Soc `PROCAR` handling and more
SMTG-UCL/easyunfold pull request #28
Opened 2023-08-01 22:30 UTC by kavanase

This is mainly a fix to update the `PROCAR` handling in `easyunfold` (also updating to make the `Procar` object JSON serializable), and in particular updating to handle SOC (ncl) `PROCAR`s. This is now dynamically determined within the `Procar` parsing code, so when plotting via the CLI the user doesn't need to specify `--ncl` (previously this information wasn't passed on to the `PROCAR` parsing anyway).

This fixes the cases I found where plotting failed due to crashes when trying to parse SOC `PROCAR`s, now fixed, giving some nice plots like this:
![image](https://github.com/SMTG-UCL/easyunfold/assets/51478689/c8d56e78-5840-48bc-85ab-7e3b42a4310d)

I've also checked through with previous example cases (NaBiS$_2$, MgO) to confirm the code is working as expected.

This also implements some other fixes:
- Removing all x/y ticks in the `sumo` DOS plots.
- Using the `sumo` orbital colour settings if atom projections aren't used and the user doesn't specify
- Docs updates
- Deprecation notices for `vscale`

2023-08-01 22:51 UTC, kavanase commented
This was based off the recently merged `dos-plotting` branch, so the new commits are the ones from [f821de2](https://github.com/SMTG-UCL/easyunfold/pull/28/commits/f821de2178d58fe3fed5ae0b22886bbd7cc59023) on

2023-08-07 12:14 UTC, kavanase commented
Hi @zhubonan!
So when plotting the atom projections for my Cs$_2$(Sn/Ti)X$_6$ alloys, I realised something a little odd. If you look at the `Sn s` - `Br -p` conduction band in this GIF:
![CSTB_Easyunfold](https://github.com/SMTG-UCL/easyunfold/assets/51478689/d4d60ae1-3c25-43e0-9b38-6d658ac364f5)
or static plot below, you can see that intensity of this band appears quite weak (and doesn't look like a mix between green/blue, just faded grey), and also in the pure Cs$_2$SnBr$_6$ material, it looks basically just blue, despite it being a 50/50 mix of `Sn s` (green) and `Br p` (blue) as you can see from the DOS:
![Sn50_Ti50_unfold_projections_intensity_3](https://github.com/SMTG-UCL/easyunfold/assets/51478689/9d158207-7a49-409d-b170-5b0d64f97378)

But if I swap the colour choice, so that `Ti` is green and `Sn` is red, then the colour looks more reasonable/intuitive and more intense/visible:
![Sn50_Ti50_unfold_projections_intensity_3_swapped_colours](https://github.com/SMTG-UCL/easyunfold/assets/51478689/f6752395-bde2-4a19-a051-5cd47cd0dece)

I dug around for a long while trying to find the origin of this, and how it could be improved. Basically it's related to how the interpolation is done in the transformed LAB space, which can result in some non-intuitive behaviour like this, depending on the colours being mixed (as you end up interpolating into the 'white' origin centre in LAB). I checked and this is similarly the case in `sumo` (which uses the same interpolation strategy), though the lack of additional transparency (due to the spectral function intensity) and underlying black line makes it much less severe in their case (though still not totally intuitive that 50/50 green/blue gives you that colour I think):
<img width="970" alt="image" src="https://github.com/SMTG-UCL/easyunfold/assets/51478689/14df8a20-b911-4bc2-b961-21eca3b3f812">

Colorspace  |  Red-Green-Blue  |  Pastel
:-------------------------:|:-------------------------:|:-------------------------:
LAB | ![unfold_projections_intensity_3_SK_dark_lab](https://github.com/SMTG-UCL/easyunfold/assets/51478689/75ed01cc-0f8c-42d2-bda3-219e4a752644) | ![unfold_projections_intensity_3_SK_dark_other_lab](https://github.com/SMTG-UCL/easyunfold/assets/51478689/d227e1da-4d83-4e38-9f5a-4884be9ba0ea)
HSV | ![unfold_projections_intensity_3_SK_dark_hsv](https://github.com/SMTG-UCL/easyunfold/assets/51478689/5fb9f7b9-fbd4-4de1-81a7-f397ed21556c) | ![unfold_projections_intensity_3_SK_dark_other_hsv](https://github.com/SMTG-UCL/easyunfold/assets/51478689/4572c147-455c-48e6-89e1-bb87eecbca3f)
RGB | ![unfold_projections_intensity_3_SK_dark_rgb](https://github.com/SMTG-UCL/easyunfold/assets/51478689/8fde4d71-4107-4244-88ea-70684a058438) | ![unfold_projections_intensity_3_SK_dark_other_rgb](https://github.com/SMTG-UCL/easyunfold/assets/51478689/fa691b3c-8200-4596-9b49-d902eb10bea3)
XYZ | ![unfold_projections_intensity_3_SK_dark_xyz](https://github.com/SMTG-UCL/easyunfold/assets/51478689/2683942d-4d24-48df-8e0e-254a92a5ddcc)| ![unfold_projections_intensity_3_SK_dark_other_xyz](https://github.com/SMTG-UCL/easyunfold/assets/51478689/f5c9196f-971a-4d24-9b53-40ccbdacef2d)
LABlch | ![unfold_projections_intensity_3_SK_dark_lablch](https://github.com/SMTG-UCL/easyunfold/assets/51478689/6335ee76-1261-4974-8474-9c6e9126489d)  |  ![unfold_projections_intensity_3_SK_dark_other_lablch](https://github.com/SMTG-UCL/easyunfold/assets/51478689/8d1a3341-c578-4028-9f6b-94cdf701557e)
LUVlch | ![unfold_projections_intensity_3_SK_dark_luvlch](https://github.com/SMTG-UCL/easyunfold/assets/51478689/5d687c6d-9526-4304-aaa1-03fe198d474e) | ![unfold_projections_intensity_3_SK_dark_other_luvlch](https://github.com/SMTG-UCL/easyunfold/assets/51478689/f5a8c1ce-4177-4dbd-9d79-c6370850ca89)

So I did a systematic check through the different possible colourspaces, using either red-green-blue or pastel red-green-blue as the basis, with these weight choices (covering the typical mixing spectrum)
```
    weights = np.array([
        [1.0, 0.0, 0.0],
        [1.0, 0.5, 0.0],
        [0.5, 0.5, 0.0],
        [1.0, 1.0, 0.0],
        [0.5, 1.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 1.0, 0.5],
        [0.0, 0.5, 0.5],
        [0.0, 1.0, 1.0],
        [0.0, 0.5, 1.0],
        [0.0, 0.0, 1.0],
        [0.5, 0.0, 1.0],
        [0.5, 0.0, 0.5],
        [1.0, 0.0, 1.0],
        [1.0, 0.0, 0.5],
        [0.5, 0.5, 0.5]])
```
Using the red-green-blue basis:
![RGB_Colours](https://github.com/SMTG-UCL/easyunfold/assets/51478689/1d2e1e87-2b1c-47d4-b2b6-ab285e55cf7b)

Using the pastel basis:
![Other_colours](https://github.com/SMTG-UCL/easyunfold/assets/51478689/e4bf1e24-9730-447d-a579-0a9a0ab1e3cd)

My conclusions/opinions would be that (1) pastel colours are nicer, (2) RGB/XYZ/LAB make intuitive sense mostly, so suggest sticking with LAB as the default colourspace, using the pastel colours if the number of projected species is <= 3 (else red, green, blue, purple, orange, yellow as suggested by colorbrewer.org) and (3) making colorspace an optional parameter at the CLI level.
I've added these updates to the code here. If you're happy with all this then I'll update the atom/orbital-projected plots in [MgO](https://smtg-ucl.github.io/easyunfold/examples/example_mgo.html) and [NaBiS2](https://smtg-ucl.github.io/easyunfold/examples/example_nabis2.html#atom-projected-unfolded-band-structure-with-dos) examples, and we can get this merged! 😃

2023-08-07 12:16 UTC, kavanase commented
Jupyter notebook for testing and plotting these colours here if useful:
[easyunfold_colourmap_testing.ipynb.zip](https://github.com/SMTG-UCL/easyunfold/files/12279535/easyunfold_colourmap_testing.ipynb.zip)

2023-08-07 15:02 UTC, kavanase commented
Ok great! I'll update the docs to match the new defaults, and add the 'example outputs' mini section discussed offline, and then this is ready to be merged ✌️ 🏎️

2023-08-07 22:55 UTC, kavanase commented
All final bits discussed now implemented @zhubonan, this is ready to be merged! 🚀

2023-08-09 09:11 UTC, kavanase commented
Some last formatting changes added there @zhubonan.
The example outputs mini-section can be seen here: https://github.com/SMTG-UCL/easyunfold/tree/SOC-procar-handling
All ready to go.

2023-08-10 01:58 UTC, zhubonan requested changes
Thanks for the improvements!

Just one minor comment regarding closing file object in `_read` - I think `with` clause if not needed. If `Procar` receives file objects (can be streams) rather than file names/paths, we should keep these objects open .

2023-08-10 01:58 UTC, zhubonan commented on easyunfold/procar.py
> +        with fobj:
We should not preemptively close the file object here, e.g. the stream may be used by other  functions later. 
Closing the file object can be moved to the `read` method instead, if the file object is opened by that method.

2023-08-10 01:58 UTC, zhubonan commented on easyunfold/procar.py
> +            return fobj_or_path  # already a file-like object, just return it
```suggestion
            if isinstance(fobj_or_path, (str, Path)):
                return open(fobj_or_path, encoding='utf-8'), True # closed later
            return fobj_or_path, False  # already a file-like object, just return it
```
Can record if the file object is opened by the function or not.

2023-08-10 01:58 UTC, zhubonan commented on easyunfold/procar.py
> +            fobj = open_file(fobj_or_path)
```suggestion
            fobj, opened = open_file(fobj_or_path)
```

2023-08-10 01:58 UTC, zhubonan commented on easyunfold/procar.py
> +                fobj.close()  # if file was opened in this loop, close it
```suggestion
            if opened:
                fobj.close()  # if file was opened in this loop, close it
```
Something like this.

2023-08-10 01:58 UTC, zhubonan commented on easyunfold/procar.py
> +                fobj.close()  # if file was opened in this loop, close it
I think the current code is fine - just that there is no need to use `with` inside `_read` method.

2023-08-10 02:08 UTC, zhubonan commented
Also, now `Procar` is `MSONable`, we should be able to store it inside the `easyunfold.json` file and/or as a separate file? This way people can get rid of the PROCAR, but I am not sure the space-saving would be much if everything is compressed.

2023-08-10 08:11 UTC, kavanase commented
Hi @zhubonan!
Have now removed the `with` statement from the `_read` method as requested.

About saving the `PROCAR` info to JSON, I was thinking this as well and tried it, but it turned out from testing a few cases that the IO speed from saving/loading the JSON was basically the same as reading the PROCAR from scratch, so there was no benefit in speedup from saving the PROCAR info to JSON. Also the file size was essentially the same as the PROCAR file size, so no file size reduction benefit either.
A disadvantage to this as well is that if it was saved in the `easyunfold.json` file then it would cause normal plotting functions (without projections) to be much slower as it would take much longer to load the large JSON file.

That said, something related I was going to mention, I think the loops in `PROCAR` parsing and `spectral_function_from_weight_sets` could be significantly sped up by only parsing bands with energies within the `emin` - `emax` range. Currently they parse all bands and then subselect from there. 
I noticed this with the Cs$_2$Sn/TiX$_6$ alloys when trying to debug the colour projections, where I was looking at the `eng` and `sf_rgb` arrays directly, and realised they stretched from -37 to +8 eV, even though only plotting from -5 to +5 eV. This is typical of most VASP calculations, so might be worth keeping in mind as a potential route to speeding up parsing for heavier cases (like atom-projected SOC supercells). Can def wait till after the JOSS submission though! 😅

2023-08-10 08:53 UTC, zhubonan approved these changes
All good!

2023-08-10 08:54 UTC, zhubonan commented
>  I think the loops in PROCAR parsing and spectral_function_from_weight_sets could be significantly sped up by only parsing bands with energies within the emin - emax range. Currently they parse all bands and then subselect from there.

Good point 👍 , can probably implement it later!

Yeah , I agree there is not much point to save PROCAR in JSON for now.

2023-08-10 08:55 UTC, merged

2023-08-10 08:56 UTC, zhubonan commented
Merged! Thanks again for fixing the PROCAR SOC bug and adding secondary axis DOS plot 🎊